name: four_in_one_app
description: "Four-in-one productivity growth app."
publish_to: 'none'
version: 2.1.0+210

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^21.0.0
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
